#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           BLMotor,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FLMotor,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FMLMotor,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BMLMotor,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           FRMotor,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           FMRMotor,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BMRMotor,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           MGMotor,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           CageMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          BRMotor,       tmotorVex393HighSpeed_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "GyroLib2.c"

int maxSpeed = 127;


//PID CONSTANTS
float kP = 0.1;
float kI = 0.00001;//0.00008;//0.0000008;
float kD = 0;//0.3;
float kC = 0.5;//6.5;

float kP_turn = 0.7;
float kI_turn = 0;
float kD_turn = 1.5;

float distance, degrees;
int turnDir;

float error, drivePower, sumError, driftError, driftCorrection;
float MAX_INTEGRAL_VALUE = 50;
float integralActiveZone = 0.0;
float wheelDiameter = 4.0;

float derivative, lastError;
float turnDerivative, lastTurnError;

//methods
void LeftDrive(int power)
{
	motor[FLMotor] = power;
	motor[FMLMotor] = power;
	motor[BMLMotor] = power;
	motor[BLMotor] = power;
}
void RightDrive(int power)
{
	motor[FRMotor] = power;
	motor[FMRMotor] = power;
	motor[BMRMotor] = power;
	motor[BRMotor] = power;
}

void driveTime(int power, int time)
{
	LeftDrive(power);
	RightDrive(power);
	wait1Msec(time);
	LeftDrive(0);
	RightDrive(0);
}

float inchesToTicks(float inches)
{
	return (inches/(4.0*PI))*360.0;
}

void mobileGoalDown(int duration)
{
	motor[MGMotor] = maxSpeed;
	wait1Msec(duration);
	motor[MGMotor] = 0;
}

void mobileGoalUp(int duration)
{
	motor[MGMotor] = -maxSpeed;
	wait1Msec(duration);
	motor[MGMotor] = 0;
}

void cageDown(int duration)
{
	motor[CageMotor] = maxSpeed;
	wait1Msec(duration);
	motor[CageMotor] = 0;
}

void cageUp(int duration)
{
	motor[CageMotor] = -maxSpeed;
	wait1Msec(duration);
	motor[CageMotor] = 0;
}

void pidDriveLoop(float targetTicks)
{
	//reset all values
	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;
	error = drivePower = sumError = driftCorrection = integralActiveZone = 0;

	//set integral active zone to 1/8 of total distance
	integralActiveZone = targetTicks * .125;

	//track right encoder
	while (SensorValue[RightEncoder] != targetTicks)
	{
		//Limit drive power
		if (drivePower > maxSpeed)
		{
			drivePower = maxSpeed;
		}
		if (drivePower < -maxSpeed)
		{
			drivePower = -maxSpeed;
		}

		//Proportional
		error = targetTicks - SensorValue[RightEncoder];

		//Integral
		if (abs(error) < inchesToTicks(integralActiveZone))
		{
			sumError += error;
		}
		else
		{
			sumError = 0;
		}

		//limit integral value
		if ((sumError*kI) > MAX_INTEGRAL_VALUE)
		{
			sumError = MAX_INTEGRAL_VALUE / kI;
		}

		if (error == 0)
		{
			derivative = 0;
		}

		//Derivative
		derivative = error - lastError;
		lastError = error;

		//Drift correction
		driftError = SensorValue[RightEncoder] - SensorValue[LeftEncoder];
		driftCorrection = driftError * kC;

		drivePower = kP * error + kI * sumError + kD * derivative;

		RightDrive(drivePower - driftCorrection);
		LeftDrive(drivePower + driftCorrection);
		//RightDrive(drivePower);
		//LeftDrive(drivePower);

		wait1Msec(25);
	}
}

void pidTurnLoop(float targetDegrees, int direction)
{
	targetDegrees = targetDegrees * 10.0;
	integralActiveZone = .125 * targetDegrees;

	SensorValue[gyro] = 0;

	//Turn left
	if (direction == 0)
	{
		while (abs(SensorValue[gyro]) != targetDegrees)
		{
			//Limit drive power
			if (drivePower > maxSpeed)
			{
				drivePower = maxSpeed;
			}
			if (drivePower < -maxSpeed)
			{
				drivePower = -maxSpeed;
			}

			//Proportional
			error = targetDegrees - abs(SensorValue[gyro]);

			//Integral
			if (error < integralActiveZone)
			{
				sumError += error;
			}
			if (error > integralActiveZone)
			{
				sumError = 0;
			}
			if ((sumError * kI_turn) > MAX_INTEGRAL_VALUE)
			{
				sumError = MAX_INTEGRAL_VALUE / kI_turn;
			}

			//Derivative
			turnDerivative = error - lastTurnError;
			lastTurnError = error;

			//Set motor power
			drivePower = kP_turn * error + kI_turn * sumError + kD_turn * turnDerivative;
			LeftDrive(-drivePower);
			RightDrive(drivePower);

			wait1Msec(25);
		}
	}

	//Turn Right
	if (direction == 1)
	{
		while (abs(SensorValue[gyro]) != targetDegrees)
		{
			//Limit drive power
			if (drivePower > maxSpeed)
			{
				drivePower = maxSpeed;
			}
			if (drivePower < -maxSpeed)
			{
				drivePower = -maxSpeed;
			}

			//Proportional
			error = targetDegrees - abs(SensorValue[gyro]);

			//Integral
			if (error < integralActiveZone)
			{
				sumError += error;
			}
			if (error > integralActiveZone)
			{
				sumError = 0;
			}
			if ((sumError * kI_turn) > MAX_INTEGRAL_VALUE)
			{
				sumError = MAX_INTEGRAL_VALUE / kI_turn;
			}

			//Derivative
			turnDerivative = error - lastTurnError;
			lastTurnError = error;

			//Set motor power
			drivePower = kP_turn * error + kI_turn * sumError + kD_turn * turnDerivative;
			LeftDrive(drivePower);
			RightDrive(-drivePower);

			wait1Msec(25);
		}
	}
}

task driveDistance
{
	pidDriveLoop(inchesToTicks(distance));
}

task turnDegrees
{
	pidTurnLoop(degrees, turnDir);
}

void driveStraight(float dist, int duration)
{
	distance = dist;
	startTask(driveDistance);
	wait1Msec(duration);
	stopTask(driveDistance);
	LeftDrive(0);
	RightDrive(0);
}

void turn(float deg, float dir, int duration)
{
	degrees = deg;
	turnDir = dir;
	startTask(turnDegrees);
	wait1Msec(duration);
	stopTask(turnDegrees);
	LeftDrive(0);
	RightDrive(0);
}

void runLeftCage()
{
	kP_turn = 0.4;
	kD_turn = 0.05;
	turn(18, 1, 300);
	driveStraight(51, 2200);
	kP_turn = 0.7;
	kD_turn = 1.5;
	turn(62, 0, 850);
	driveStraight(-56.0, 2300);
	kP_turn = 0.4;
	kD_turn = 0.05;
	turn(10, 0, 300);
	cageDown(1000);
}

void runRightCage()
{
	kP_turn = 0.4;
	kD_turn = 0.05;
	turn(25, 0, 350);
	driveStraight(47, 2200);
	kP_turn = 0.7;
	kD_turn = 1.5;
	turn(72, 1, 850);
	driveStraight(-56.0, 2300);
	kP_turn = 0.4;
	kD_turn = 0.05;
	turn(10, 1, 300);
	cageDown(1000);
}

void runRightDamage()
{
	kP_turn = 0.4;
	kD_turn = 0.05;
	turn(18, 0, 300);
	driveStraight(64, 2000);
	kP_turn = 0.7;
	kD_turn = 1.5;
	turn(118, 1, 1100);
	driveStraight(-63, 2400);
}

void runLeftDamage()
{
	kP_turn = 0.4;
	kD_turn = 0.05;
	turn(18, 1, 300);
	driveStraight(79, 3000);
	kP_turn = 0.7;
	kD_turn = 1.5;
	turn(131, 0, 1100);
	driveStraight(-63, 2400);
}


void oneCage()
{
	driveStraight(-34, 1500);
	cageDown(1000);
}

task main()
{
	//gyro initialize
	GyroInit();
	SensorType[in1] = sensorNone;
	wait1Msec(1000);
	SensorType[in1] = sensorGyro;
	wait1Msec(1000);
	SensorValue[LeftEncoder] = 0;
	SensorValue[RightEncoder] = 0;

	while (true)
	{
		if (vexRT[Btn8U] == 1)
		{
			runLeftDamage();
		}
	}
}
