#pragma config(Sensor, in8,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  LeftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  RightEncoder,   sensorQuadEncoder)
#pragma config(Motor,  port1,           MGMotor,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FLMotor,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           BLMotor,       tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           LLiftMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LChainbarMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           FRMotor,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           BRMotor,       tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           RLiftMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           RChainbarMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          IntakeMotor,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#pragma systemFile   // eliminates warning for "unreferenced" functions
/*---------------------------------------------------------------------------*/
/*                                                                           */
/*     					   Description: Competition code for 2019B							     */
/*                                                                           */
/*---------------------------------------------------------------------------*/
// This code is for the VEX cortex platform7
#pragma platform(VEX2)
// Select Download method as "competition"
#pragma competitionControl(Competition)
//Main competition background code...
#include "Vex_Competition_Includes.c"
#include "AutonomousRight.c"
#include "UserDriving.c" // User controlled joystick/gamepad code
#include "AutonomousCones.c" //Pick up cones
#include "AutonomousStationary.c" //Stationary Auton
#include "Autonomous10Right.c" //10 Point Auton on right side of field
#include "Autonomous10Left.c" //10 Point Auton on left side of field
#include "Autonomous5Left.c" //5 Point Auton on left side of field
#include "Autonomous5Right.c" //5 Point Auton on right side of field
#include "LCD.c" // Functions for the LCD
#include "gyroLib2.c" // Gyro library fuctions
#include "Autonomous24Left.c"
#include "Autonomous24Right.c"


/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/* 							  Functions and pre-match (autonomous) setup 						   	 */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	GyroInit();
	SensorType[in1] = sensorNone;
	wait1Msec(1000);
	SensorType[in1] = sensorGyro;
	wait1Msec(1000);
	lcdSetup();
	autonSelectUI();
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task autonomous(){
	switch(count){
	case 0:
		displayLCDCenteredString(0, "Running 22autoRight");
		runAutonRight();
		break;
	case 1:
		displayLCDCenteredString(0, "Running 22autoLeft");
		runAutonLeft();
		break;
	case 2:
		displayLCDCenteredString(0, "Running inspect");
		LeftDrive(maxSpeed);
		RightDrive(maxSpeed);
		wait1Msec(1000);
		LeftDrive(0);
		RightDrive(0);
		break;
	case 3:
		displayLCDCenteredString(0, "Running autoCones");
		runAutonCones();
		break;
	case 4:
		displayLCDCenteredString(0, "Running stationary");
		runAutonStationary();
		break;
	case 5:
		displayLCDCenteredString(0, "Running 10Right");
		runAuton10Right();
		break;
	case 6:
		displayLCDCenteredString(0, "Running 10Left");
		runAuton10Left();
		break;
	case 7:
		displayLCDCenteredString(0, "Running 5Right");
		runAuton5Right();
		break;
	case 8:
		displayLCDCenteredString(0, "Running 5Left");
		runAuton5Left();
		break;
	case 9:
		displayLCDCenteredString(0, "Running 24AutonRight");
		runAuton24Right();
		break;
	case 10:
		displayLCDCenteredString(0, "Running 24AutonLeft");
		runAuton24Left();
		break;
	case 11:
		displayLCDCenteredString(0, "Running nothing");
		break;
	default:
		displayLCDCenteredString(0, "No valid choice");
		displayLCDCenteredString(1, "was made!");
		break;

	}
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	displayLCDCenteredString(0, "Tele-OP");

	while (true)
	{
		arcadeDrive();
	}

}
/*---------------------------------------------------------------------------*/
/*                                 Notes                                     */
/*---------------------------------------------------------------------------*/
